version: '2.0'
services:
  redis: 
    container_name: redis
    hostname: redis
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "@db.password1"]
    ports:
        - "6379:6379"
    volumes:
        - $PWD/../data/redis:/var/lib/redis
        - $PWD/redis.config:/usr/local/etc/redis/redis.conf
  mongodb:
    container_name: mongo
    hostname: mongo
    image: "mongo:latest"
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf
      # - ./mongodb/initdb.d:/docker-entrypoint-initdb.d
      - ../data/mongodb:/data/db
      - ../data/mongodb-log:/var/log/mongodb
      - ../data/home/mongodb:/home/mongodb
    # command: [ "-f", "/etc/mongod.conf" ]
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: TestWont123org
        MONGO_INITDB_DATABASE: mydb
        # MONGO_INITDB_USERNAME: myTester
        # MONGO_INITDB_PASSWORD: testWont123org
    ports:
      - "27017:27017"
    


